trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build - $(BuildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Functional tests - $(BuildConfiguration)'
  inputs:
    command: 'test'
    arguments: '--configuration $(BuildConfiguration) --collect:"XPlat Code Coverage"'

- task: DotNetCoreCLI@2
  displayName: 'Performance tests - $(BuildConfiguration)'
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/perf'
    command: 'run'
    arguments: '--configuration $(BuildConfiguration)'