trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build 
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'

- task: Bash@3
  continueOnError: true
  inputs:
    targetType: 'inline'
    script: 'pwd && cd perf && pwd'

- task: DotNetCoreCLI@2
  displayName: Performance
  inputs:
    command: 'run'
    configuration: 'Release'