trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build 
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'

- task: DotNetCoreCLI@2
  displayName: Performance
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/perf'
    command: 'run'
    configuration: 'Release'